import { ProjectsInformationType } from '@src/types/contents/projects';

export const projectsInformation: ProjectsInformationType[] = [
  {
    id: 0,
    title: 'Hanssak 디자인 시스템',
    period: '2024.06 ~ 2024.12',
    skills: [
      'HTML',
      'CSS',
      'javascript',
      'react',
      'typescript',
      'tailwindcss',
      'google material icon',
      'storybook',
      'eslint',
      'prettier',
      'git',
    ],
    progress: 0,
    image: 'design_system.png',
  },
  {
    id: 1,
    title: '보안 솔루션 고도화',
    period: '2023.06 ~ 2025.01',
    skills: [
      'HTML',
      'CSS',
      'javascript',
      'react',
      'next.js',
      'redux',
      'mui',
      'docker',
      'eslint',
      'prettier',
      'git',
    ],
    progress: 0,
    image: 'solution.png',
  },
  {
    id: 2,
    title: '웹 플랫폼 고도화',
    period: '2022.01 ~ 2023.06',
    skills: [
      'CSS',
      'javascript',
      'react',
      'next.js',
      'redux',
      'mui',
      'storybook',
      'eslint',
      'prettier',
      'git',
    ],
    progress: 0,
    image: 'platform.png',
  },
  {
    id: 3,
    title: '보안 솔루션 프로토타입 구축',
    period: '2022.04 ~ 2024.06',
    skills: [
      'CSS',
      'javascript',
      'react',
      'next.js',
      'redux',
      'mui',
      'storybook',
      'eslint',
      'prettier',
      'git',
    ],
    progress: 0,
    image: 'prototype.svg',
  },

  {
    id: 4,
    title: '개인 포트폴리오',
    period: '2025.03 ~ 진행중',
    skills: [
      'HTML',
      'CSS',
      'javascript',
      'typescript',
      'react',
      'next.js',
      'redux',
      'tailwindcss',
      'google material icon',
      'eslint',
      'prettier',
      'git',
    ],
    progress: 1,
    image: 'portfolio.png',
  },
];
